https://segmentfault.com/q/1010000004263937?_ea=549435

如果你使用声明式事务管理，`@Transactional`，默认情况下所有的 `RuntimeException` 会触发回滚，所有的 `checked Exception` 不会触发回滚。你可以通过 `rollback-for` 和 `no-rollback-for` 来调整这个配置。如果你 catch 住异常，不再抛出，异常没办法到事务管理器中，不会触发回滚操作。

注释：@Transactional(rollbackFor = Exception.class)